export default [
  {
    id: 1,
    regNo: 'S001',
    firstName: 'Alice',
    lastName: 'Johnson',
    gender: 'Female',
    form: 'Form 1',
  },
  {
    id: 2,
    regNo: 'S002',
    firstName: 'Bob',
    lastName: 'Smith',
    gender: 'Male',
    form: 'Form 2',
  },
  {
    id: 3,
    regNo: 'S003',
    firstName: 'Charlie',
    lastName: 'Brown',
    gender: 'Male',
    form: 'Form 3',
  },
  {
    id: 4,
    regNo: 'S004',
    firstName: 'David',
    lastName: 'Wilson',
    gender: 'Male',
    form: 'Form 1',
  },
  {
    id: 5,
    regNo: 'S005',
    firstName: 'Eve',
    lastName: 'Davis',
    gender: 'Female',
    form: 'Form 2',
  },
  {
    id: 1,
    regNo: 'S001',
    firstName: 'Alice',
    lastName: 'Johnson',
    gender: 'Female',
    form: 'Form 1',
  },
  {
    id: 2,
    regNo: 'S002',
    firstName: 'Bob',
    lastName: 'Smith',
    gender: 'Male',
    form: 'Form 2',
  },
  {
    id: 3,
    regNo: 'S003',
    firstName: 'Charlie',
    lastName: 'Brown',
    gender: 'Male',
    form: 'Form 3',
  },
  {
    id: 4,
    regNo: 'S004',
    firstName: 'David',
    lastName: 'Wilson',
    gender: 'Male',
    form: 'Form 1',
  },
  {
    id: 5,
    regNo: 'S005',
    firstName: 'Eve',
    lastName: 'Davis',
    gender: 'Female',
    form: 'Form 2',
  },

  {
    id: 1,
    regNo: 'S001',
    firstName: 'Alice',
    lastName: 'Johnson',
    gender: 'Female',
    form: 'Form 1',
  },
  {
    id: 2,
    regNo: 'S002',
    firstName: 'Bob',
    lastName: 'Smith',
    gender: 'Male',
    form: 'Form 2',
  },
  {
    id: 3,
    regNo: 'S003',
    firstName: 'Charlie',
    lastName: 'Brown',
    gender: 'Male',
    form: 'Form 3',
  },
  {
    id: 4,
    regNo: 'S004',
    firstName: 'David',
    lastName: 'Wilson',
    gender: 'Male',
    form: 'Form 1',
  },
  {
    id: 5,
    regNo: 'S005',
    firstName: 'Eve',
    lastName: 'Davis',
    gender: 'Female',
    form: 'Form 2',
  },
  {
    id: 1,
    regNo: 'S001',
    firstName: 'Alice',
    lastName: 'Johnson',
    gender: 'Female',
    form: 'Form 1',
  },
  {
    id: 2,
    regNo: 'S002',
    firstName: 'Bob',
    lastName: 'Smith',
    gender: 'Male',
    form: 'Form 2',
  },
  {
    id: 3,
    regNo: 'S003',
    firstName: 'Charlie',
    lastName: 'Brown',
    gender: 'Male',
    form: 'Form 3',
  },
  {
    id: 4,
    regNo: 'S004',
    firstName: 'David',
    lastName: 'Wilson',
    gender: 'Male',
    form: 'Form 1',
  },
  {
    id: 5,
    regNo: 'S005',
    firstName: 'Eve',
    lastName: 'Davis',
    gender: 'Female',
    form: 'Form 2',
  },

  // Add more sample data if needed
]
